# Generated by Django 4.2.4 on 2023-08-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile',
        ),
    ]
