# Generated by Django 4.2.4 on 2023-08-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Chef de service', 'Chef de service'), ("Directeur de l'informatique", "Directeur de l'informatique"), ('Chef réseau', 'Chef réseau')], default='Chef de service', max_length=50),
        ),
    ]
