# Generated by Django 4.1.7 on 2023-08-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Chef de service', 'Chef de service'), ("Directeur de l'informatique", "Directeur de l'informatique"), ('Chef réseau', 'Chef réseau')], max_length=50),
        ),
    ]
