# Generated by Django 4.2.4 on 2023-08-09 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0002_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='cerated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
