# Generated by Django 4.1.7 on 2023-08-16 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cruds', '0004_uploadedfile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruds.uploadedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PdfDocument',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='users_with_access',
            field=models.ManyToManyField(through='cruds.FileAccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
