# Generated by Django 4.1.7 on 2023-08-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0005_fileaccess_delete_pdfdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccess',
            name='has_access',
            field=models.BooleanField(default=False),
        ),
    ]
